import discord
from discord.ext import commands
import time
import aiohttp
import io
from zalgo_text import zalgo as zalgo_text_gen

class misc(commands.Cog):
    def __init__(self, bot):
        self.bot = bot

    @commands.command(aliases=["owner"])
    async def hi(self, ctx):
        await ctx.send("Hello! I'm a robot. tk421#7244 made me!")

    @commands.command(help="zalgo text")
    async def zalgo(self, ctx, *, arg):
        await ctx.send(zalgo_text_gen.zalgo().zalgofy(str(arg)))

    @commands.command(help="Get an image of a cat. The image is generated by AI, therefore it's an image of a cat that doesn't exist", aliases=["cats"])
    async def thiscatdoesntexist(self, ctx):
        await ctx.trigger_typing()
        async with aiohttp.ClientSession() as cs:
            async with cs.get('https://thiscatdoesnotexist.com') as r:
                buffer = io.BytesIO(await r.read())
                await ctx.send(file=discord.File(buffer, filename="cat.jpeg"))

    async def exectime(self, start_time, ctx):
        await ctx.send("took " + str(round(time.time()-start_time, 2)) + " seconds to execute")

    @commands.command(aliases=['pong'])
    async def ping(self, ctx):
        await ctx.send("Pong! My latency is " + str(round(self.bot.latency*1000, 1)) + "ms.")

    @commands.command(help="Get some info about the bot")
    async def about(self, ctx):
        embed = discord.Embed(title="About", color=discord.Color.blurple())
        embed.add_field(name="Useful links", value="Use `" + str(self.bot.command_prefix) + "help command` for more info on a certain command. \n For more help, join the support server at https://discord.gg/PJ94gft. \n To add Maximilian to your server, with only the required permissions, click [here](https://discord.com/api/oauth2/authorize?client_id=620022782016618528&permissions=268815456&scope=bot).", inline=False)
        embed.add_field(name="Fun Commands", value="Commands that have no purpose. \n `zalgo` `cats` `ping`", inline=True)
        embed.add_field(name="Other Commands", value="Commands that actually have a purpose. \n `about` `help` `userinfo` `reactionroles` `responses` `prefix` `listprefixes` `hi`", inline=True)
        await ctx.send(embed=embed)

    @commands.is_owner()
    @commands.command(hidden=True)
    async def listguildnames(self, ctx):
        guildstring = ""
        for each in self.bot.guilds:
            guildstring = guildstring + each.name + ", "
        await ctx.send(guildstring[:-2])

    @commands.command(help="Get information about a certain user, including status, roles, profile picture, and permissions", aliases=['getuserinfo'])
    async def userinfo(self, ctx):
        start_time = time.time()
        await ctx.trigger_typing()
        rolestring = ""
        permissionstring = ""
        if ctx.message.mentions is not None and ctx.message.mentions != []:
            requested_user = ctx.message.mentions[0]
        else:
            requested_user = ctx.message.author
        status = requested_user.status[0]
        statusnames = {"online" : "Online", "dnd" : "Do Not Disturb", "idle" : "Idle", "offline" : "Invisible/Offline"}
        statusemojis = {"online" : "<:online:767294866488295475>", "dnd": "<:dnd:767510004135493662>", "idle" : "<:idle:767510329139396610>", "offline" : "<:invisible:767510747466170378>"}
        if len(requested_user.roles) == 1:
            rolecolor = discord.Color.blurple()
        else:
            rolecolor = requested_user.roles[len(requested_user.roles)-1].color
        embed = discord.Embed(title=f"User info for {str(requested_user.name)}#{str(requested_user.discriminator)}", color=rolecolor)
        embed.add_field(name="Date joined:", value=requested_user.joined_at.strftime("%B %d, %Y"), inline=False)
        embed.add_field(name="Date created:", value=requested_user.created_at.strftime("%B %d, %Y"), inline=False)
        for each in requested_user.roles:
            if each.name != "@everyone":
                rolestring = rolestring + "<@&" + str(each.id) + ">, "
            else:
                rolestring = rolestring + each.name + ", "
        for each in requested_user.guild_permissions:
            if each[1] == True:
                permissionstring = f"{permissionstring}{each[0].replace('_', ' ').capitalize()}, "
        rolestring = rolestring[:-2]
        permissionstring = permissionstring[:-2]
        embed.add_field(name="Roles:", value=rolestring, inline=False)
        embed.add_field(name="Permissions:", value=permissionstring, inline=False)
        embed.add_field(name="Status:", value=f"{statusemojis[status]} {statusnames[status]}", inline=False)
        if requested_user.activity == None:
            statusinfo = "No status details available"
        else:
            if requested_user.activity.type.name is not None and requested_user.activity.type.name != "custom":
                activitytype = requested_user.activity.type.name.capitalize()
            else:
                activitytype = ""
            statusinfo = f"Status details: '{activitytype} {requested_user.activity.name}'"
        executiontime = f"took {str(round(time.time()-start_time, 2))} seconds to execute"
        if requested_user.id == self.bot.owner_id:
            embed.set_footer(text=f"{statusinfo}  |  Requested by {ctx.author.name}#{ctx.author.discriminator}  |  This is my owner's info!  |    {executiontime}")
        else:
            embed.set_footer(text=f"{statusinfo}  |  Requested by {ctx.author.name}#{ctx.author.discriminator}  |   {executiontime}")
        embed.set_thumbnail(url=requested_user.avatar_url)
        await ctx.send(embed=embed)


def setup(bot):
    bot.add_cog(misc(bot))

def teardown(bot):
    bot.remove_cog(misc(bot))